services:
  - type: web
    name: on-prize-backend
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: On-Prize
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 4000
      - key: DB_DATABASE
        value: test
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: MYSQL_ATTR_SSL_CA
        value: /tmp/isrgrootx1.pem
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
